id: Evening lights
alias: Evening lights
hide_entity: false
trigger:
- platform: sun
  event: sunset
  offset: -00:45:00
condition:
  condition: state
  entity_id: device_tracker.ce0517156d28ecf70d
  state: home
action:
- service: homeassistant.turn_on
  data:
    entity_id: light.badtak
    brightness: 237
    color_temp: 358
- service: homeassistant.turn_on
  data:
    entity_id: light.inngangtak
    brightness: 237
    color_temp: 358
- service: homeassistant.turn_on
  data:
    entity_id: light.stuetak
    brightness: 237
    color_temp: 358
- service: homeassistant.turn_on
  data:
    entity_id: light.hue_color_lamp_1
    brightness: 206
    color_temp: 153
    rgb_color: 255,128,69
- service: homeassistant.turn_on
  data:
    entity_id: light.hue_color_candle_1
    brightness: 206
    color_temp: 375
    rgb_color: 255,219,86