id: update_morning_commute_sensor
alias: "Commute - Update morning commute sensor"
initial_state: 'on'
trigger:
  - platform: time
    minutes: '/2'
    seconds: 00
condition:
  - condition: time
    after: '07:00:00'
    before: '09:00:00'
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
action:
  - service: sensor.google_travel_sensor_update
    data:
      entity_id: sensor.google_travel_time__driving