
# Use this file to store secrets like usernames and passwords.
# Learn more at https://home-assistant.io/docs/configuration/secrets/
http_password: notreal

gpslogger_password: notreal

carnet_password: notreal
carnet_username: notreal

darksky_api: notreal

mqtt_username: notreal
mqtt_password: notreal!

spotify_client_id: notreal
spotify_secret: notreal

tibber_accesstoken: notreal

influx_password: notreal

#Locations
latitude_oav35: 0.0
longitude_oav35: 0.0

latitude_work: 0.0
longitude_work: 0.0

latitude_box: 0.0
longitude_box: 0.0

googleapikey: notreal